kni: fix compilation with gcc 6.1
Using gcc 6.1, in some cases, kni fails to compile
because of unused variables:

build/lib/librte_eal/linuxapp/kni/ixgbe_main.c:82:19:
error: ‘ixgbe_copyright’
defined but not used [-Werror=unused-const-variable=]
static const char ixgbe_copyright[] =
                   ^~~~~~~~~~~~~~~

build/lib/librte_eal/linuxapp/kni/ixgbe_main.c:62:19:
error: ‘ixgbe_driver_string’
defined but not used [-Werror=unused-const-variable=]
static const char ixgbe_driver_string[] =

Fixes: 3fc5ca2f6352 ("kni: initial import")

Signed-off-by: Pablo de Lara <pablo.de.lara.guarch@intel.com>