net: fix missing include in exported header
This commit addresses the following errors:

 In file included from /tmp/check-includes.sh.18889.c:1:0:
 build/include/rte_net_crc.h:86:1: error: unknown type name 'uint32_t'
 [...]

Fixes: 986ff526fb84 ("net: add CRC computation API")

Cc: Jasvinder Singh <jasvinder.singh@intel.com>
Signed-off-by: Adrien Mazarguil <adrien.mazarguil@6wind.com>