examples: ethtool: Link against librte_pmd_ixgbe if necessary
The librte_ethtool library depends on librte_pmd_ixgbe if that
pmd driver is enabled so we need to link against it when we compile
the ethtool application. It fixes the following build problem:

/usr/lib64/gcc/x86_64-suse-linux/6/../../../../x86_64-suse-linux/bin/ld:
warning: librte_pmd_ixgbe.so.1, needed by /home/abuild/rpmbuild/BUILD/
dpdk-17.02/examples/ethtool/lib/x86_64-native-linuxapp-gcc/lib/
librte_ethtool.so, not found (try using -rpath or -rpath-link)
/home/abuild/rpmbuild/BUILD/dpdk-17.02/examples/ethtool/lib/
x86_64-native-linuxapp-gcc/lib/librte_ethtool.so: undefined reference to
`rte_pmd_ixgbe_set_vf_rxmode@DPDK_17.02'
collect2: error: ld returned 1 exit status

Cc: Nirmoy Das <ndas@suse.de>
Signed-off-by: Markos Chandras <mchandras@suse.de>