armv7a: disable qede pmd
The qede PMD driver is failing when building for ARMv7:

drivers/net/qede/base/ecore_dev.c: In function ‘ecore_hw_init_pf’:
drivers/net/qede/base/ecore_dev.c:1150:6:
	error: variable ‘prs_reg’ set but not used [-Werror=unused-but-set-variable]
  u32 prs_reg;
      ^
[...]

drivers/net/qede/base/ecore_dev.c:2492:13:
	error: variable ‘p_phys’ set but not used [-Werror=unused-but-set-variable]
  dma_addr_t p_phys = p_chain->p_phys_addr, p_phys_next = 0;
             ^
drivers/net/qede/base/ecore_dev.c: In function ‘ecore_chain_free_pbl’:
drivers/net/qede/base/ecore_dev.c:2532:39:
	error: variable ‘pbl_size’ set but not used [-Werror=unused-but-set-variable]
  u32 page_cnt = p_chain->page_cnt, i, pbl_size;

Fixes: 3eae93a9bfd5 ("qede: enable PMD build")

Signed-off-by: Jan Viktorin <viktorin@rehivetech.com>