lpm: fix build error on g++ with -O0 option
When rte_lpm.h is used on x86, -O0 option (no optimization at all)
given to g++ (not gcc) causes a compile error like this:

error: the last argument must be an 8-bit immediate
   i24 = _mm_srli_si128(i24, sizeof(uint64_t));

-O0 option is useful for debugging and code coverage measurement, but
this error prevents C++ programs from building. This patch replaces
"sizeof(uint64_t)" with a constant literal "8" to work around the issue.
Tested with g++ 5.4.1.

Signed-off-by: Sangjin Han <sangjin@eecs.berkeley.edu>