bitrate: fix errors in exported header
This commit addresses the following error:

 In file included from /tmp/check-includes.sh.28023.c:1:0:
 build/include/rte_bitrate.h:82:2: error: unknown type name 'uint8_t'
 [...]

It also adds C++ awareness to rte_bitrate.h.

Fixes: 2ad7ba9a6567 ("bitrate: add bitrate statistics library")

Cc: Remy Horton <remy.horton@intel.com>
Signed-off-by: Adrien Mazarguil <adrien.mazarguil@6wind.com>