mbuf: fix missing includes in exported header
This commit addresses the following errors:

 In file included from /tmp/check-includes.sh.681.c:1:0:
 build/include/rte_mbuf_ptype.h:587:35: error: unknown type name 'uint32_t'
 [...]
 build/include/rte_mbuf_ptype.h:662:51: error: unknown type name 'size_t'
 [...]

Fixes: 288541c8ff9e ("mbuf: add functions to dump packet type")

Cc: stable@dpdk.org
Cc: Olivier Matz <olivier.matz@6wind.com>
Signed-off-by: Adrien Mazarguil <adrien.mazarguil@6wind.com>