latency: fix missing includes in exported header
This commit addresses the following errors:

 In file included from build/include/rte_latencystats.h:43:0,
                  from /tmp/check-includes.sh.6580.c:1:
 build/include/rte_metrics.h:91:2: error: unknown type name 'uint16_t'
 [...]
 In file included from /tmp/check-includes.sh.6580.c:1:0:
 build/include/rte_latencystats.h:66:19: error: expected declaration
    specifiers or '...' before '*' token
 [...]

Fixes: 5cd3cac9ed22 ("latency: added new library for latency stats")

Cc: Reshma Pattan <reshma.pattan@intel.com>
Signed-off-by: Adrien Mazarguil <adrien.mazarguil@6wind.com>