Fix misleading indentation in ethtool
gcc complains about:
build/lib/librte_eal/linuxapp/kni/e1000_phy.c:3303:2:
error: this 'if' clause does not guard... [-Werror=misleading-indentation]

Code indentation is misleadingly indented as whether
the following content is guarded by if or not.
With the reference of the context, add the curly braces.

Remove unused const variables too.

Signed-off-by: Pengyu Ma <pengyu.ma@windriver.com>